<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
  <script>
      // async函数返回一个 Promise 对象。

      // async函数内部return语句返回的值，会成为then方法回调函数的参数。  
      async function f() {
        return 'hello world';
      }

      f().then(v => console.log(v))
      // "hello world"

      // 上面代码中，函数f内部return命令返回的值，会被then方法回调函数接收到。

      // async函数内部抛出错误，会导致返回的 Promise 对象变为reject状态。抛出的错误对象会被catch方法回调函数接收到。

      async function f() {
        throw new Error('出错了');
      }

      f().then(
        v => console.log(v),
        e => console.log(e)
      )
      // Error: 出错了
  </script>
</body>

</html>